sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/.next/**,**/node_modules/**,backend/alembic/**,backend/data/**,website/**
sonar.coverage.exclusions=frontend/**,website/**,backend/scripts/**
