from __future__ import annotations

import json
import re
from collections import defaultdict

from app.db.models import Asset


def render_ansible_inventory(assets: list[Asset]) -> str:
    lines: list[str] = ["# Generated by Argus", ""]
    groups: dict[str, list[str]] = defaultdict(list)

    for asset in sorted(assets, key=lambda item: (item.device_type or "zzzz", item.hostname or item.ip_address)):
        host_name = _inventory_name(asset)
        host_line = (
            f"{host_name} ansible_host={asset.ip_address} "
            f"argus_status={_quote(asset.status)} "
            f"argus_vendor={_quote(asset.vendor or '')} "
            f"argus_device_type={_quote(asset.effective_device_type)}"
        )
        groups["argus"].append(host_line)
        groups[asset.status].append(host_name)
        groups[asset.effective_device_type].append(host_name)
        for tag in sorted({tag.tag for tag in asset.tags}):
            groups[f"tag_{tag}"].append(host_name)

    for group_name in sorted(groups):
        lines.append(f"[{_sanitize_group(group_name)}]")
        lines.extend(groups[group_name])
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def render_terraform_inventory(assets: list[Asset]) -> str:
    resources: dict[str, dict] = {}
    for asset in sorted(assets, key=lambda item: item.ip_address):
        resource_name = _resource_name(asset)
        resources[resource_name] = {
            "input": {
                "id": str(asset.id),
                "ip_address": asset.ip_address,
                "hostname": asset.hostname,
                "mac_address": asset.mac_address,
                "vendor": asset.vendor,
                "os_name": asset.os_name,
                "device_type": asset.effective_device_type,
                "status": asset.status,
                "tags": sorted(tag.tag for tag in asset.tags),
                "custom_fields": asset.custom_fields or {},
            }
        }

    payload = {
        "terraform": {"required_version": ">= 1.5.0"},
        "resource": {"terraform_data": resources},
        "output": {
            "argus_asset_count": {"value": len(assets)},
            "argus_assets": {
                "value": [
                    {
                        "id": str(asset.id),
                        "ip_address": asset.ip_address,
                        "hostname": asset.hostname,
                        "device_type": asset.effective_device_type,
                        "status": asset.status,
                    }
                    for asset in sorted(assets, key=lambda item: item.ip_address)
                ]
            },
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def build_inventory_snapshot(assets: list[Asset]) -> dict[str, object]:
    return {
        "generated_by": "Argus",
        "asset_count": len(assets),
        "assets": [
            {
                "id": str(asset.id),
                "ip_address": asset.ip_address,
                "hostname": asset.hostname,
                "mac_address": asset.mac_address,
                "vendor": asset.vendor,
                "os_name": asset.os_name,
                "os_version": asset.os_version,
                "device_type": asset.effective_device_type,
                "status": asset.status,
                "tags": sorted(tag.tag for tag in asset.tags),
                "ports": [
                    {
                        "port_number": port.port_number,
                        "protocol": port.protocol,
                        "service": port.service,
                        "version": port.version,
                        "state": port.state,
                    }
                    for port in sorted(asset.ports, key=lambda item: (item.port_number, item.protocol))
                ],
                "custom_fields": asset.custom_fields or {},
                "first_seen": asset.first_seen.isoformat(),
                "last_seen": asset.last_seen.isoformat(),
            }
            for asset in sorted(assets, key=lambda item: item.ip_address)
        ],
    }


def _inventory_name(asset: Asset) -> str:
    candidate = asset.hostname or asset.ip_address
    slug = re.sub(r"[^a-zA-Z0-9_.-]+", "_", candidate).strip("_")
    return slug or asset.ip_address.replace(".", "_")


def _resource_name(asset: Asset) -> str:
    base = asset.hostname or asset.ip_address
    slug = re.sub(r"[^a-zA-Z0-9_]+", "_", base).strip("_").lower()
    if not slug or slug[0].isdigit():
        slug = f"asset_{slug or asset.ip_address.replace('.', '_')}"
    return slug


def _sanitize_group(group_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_:-]+", "_", group_name)


def _quote(value: str) -> str:
    escaped = value.replace('"', '\\"')
    return f'"{escaped}"'
